<?php

/*
 * This file has generated by ALCAD di Alessio Chiga
 * This file has been released under the GNU/GPL.
 * Contact info@alcad.it to know more.
 */

namespace alcad\cas;

use yii\base\Object;
use yii\web\IdentityInterface;

class CasInterface implements IdentityInterface
{
	public $id;
	public $username;
	public $password;
	public $authKey;
	public $accessToken;

	public static function findIdentity($id)
	{
		return $this->username;
	}

	public static function findIdentityByAccessToken($token, $type = null)
	{
		return $this->username;
	}

	public function getId()
	{
		return $this->username;
	}

	public function getAuthKey()
	{
		return $this->authKey;
	}

	public function validateAuthKey($authKey)
	{
		return $this->authKey === $authKey;
	}
	
	public function getIsAdmin() {
		return false;
	}

}
